### ISSUE TITLE
serverless "service pattern"

### ISSUE THREAD

**Issue by pvcon13** [continuationlabs/hapi-gateway#11]
First, thanks so very much for this excellent framework.

Pretty sure this is not an issue, more like an expanded question.

1) Hapi.js deployed in container for each service (all crud for all variants on a subject noun [/user or /geo or /items or etc])

2) where all events that need inter-microservice updates are passed through a queue (rabbitMQ for example)

3) where all databases (event/audit relational and CQRS denormalized document for read) are static clusters, and each represents a service or a few related services)

4) would like all updates to the database(s) and all business logic be lambdas, where each service is one lambda front ended by Hapi.

So that would mean that Hapi is doing authentication and validation, and passing anything related to this one service to one lambda. (the hapi code listens and posts on the rabbitMQ bus.) How would you deal with that switching between Hapi service and its corresponding Lambda endpoints? Would each endpoint be selected by the lambda by a passed attribute? Or is there a better way? 

Goal is to have lambdas thick enough to stay warm (so there is not  lambda per GET or POST, but still divide up the services enough to keep code complexity for each manageable for multiple teams and features. 

Thanks for any advice and thanks again for this hapi integration . Excellent stuff :)

**Comment by cjihrig** [comment]
I would write a separate Lambda for each hapi route handler. However, if you want "thick" Lambdas, you can handle multiple routes in a single Lambda. One extreme is to run your entire hapi server in Lamba, as described [here](http://www.carbonatethis.com/hosting-a-serverless-hapi-js-api-with-aws-lambda/).

**Comment by pvcon13** [comment]
Thanks

My issue is liking the idea of Hapi locally and using containers that are tracked locally by Traefik reverse proxy. So if I create a Rancher cluster and run some orchestration system in it, like marathon, then  all the front end hapi servers for all microservices are in that cluster tracked by Traefik. 

The idea of using the aws api gateway was part of the mess I wanted to avoid. I thought that Lambdas scale much better than containers, and 90 percent of the work is after the route and authing phase (talking to the multiple Databases) for example.

I like your approach better.  Perhaps I can extend it to handle a set of of related routes.

Have you been getting a lot of downloads with this framework?

**Comment by cjihrig** [comment]
> The idea of using the aws api gateway was part of the mess I wanted to avoid.

Yea, that's pretty much why I created this module. API Gateway is... rough.

> Perhaps I can extend it to handle a set of of related routes.

That should already be possible. On the hapi side, you'd just create a route configuration object and use it with multiple routes.

> Have you been getting a lot of downloads with this framework?

I don't know of any other users. I made this for myself, but it's great if others want to use it.
